# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import qtawesome as qta

class Ui_MainWindow(object):
	def setupUi(self, MainWindow):
		MainWindow.setObjectName("MainWindow")
		MainWindow.resize(800, 600)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
		MainWindow.setSizePolicy(sizePolicy)
		self.centralwidget = QtWidgets.QWidget(MainWindow)
		self.centralwidget.setObjectName("centralwidget")
		self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
		self.gridLayout.setObjectName("gridLayout")
		self.verticalLayout = QtWidgets.QVBoxLayout()
		self.verticalLayout.setContentsMargins(-1, -1, -1, 5)
		self.verticalLayout.setObjectName("verticalLayout")
		self.horizontalLayout = QtWidgets.QHBoxLayout()
		self.horizontalLayout.setObjectName("horizontalLayout")        
		self.play_pause_btn = QtWidgets.QPushButton(self.centralwidget)
		self.play_pause_btn.setText("")
		self.play_pause_btn.setIcon(qta.icon('fa.play'))
		self.play_pause_btn.setIconSize(QtCore.QSize(24, 24))
		self.play_pause_btn.setObjectName("play_pause_btn")
		self.horizontalLayout.addWidget(self.play_pause_btn)
		self.stop_btn = QtWidgets.QPushButton(self.centralwidget)
		self.stop_btn.setText("")
		self.stop_btn.setIcon(qta.icon('fa.stop'))
		self.stop_btn.setIconSize(QtCore.QSize(24, 24))
		self.stop_btn.setObjectName("stop_btn")
		self.horizontalLayout.addWidget(self.stop_btn)
		self.label = QtWidgets.QLabel(self.centralwidget)
		font = QtGui.QFont()
		font.setPointSize(20)
		font.setBold(False)
		font.setWeight(50)
		self.label.setFont(font)
		self.label.setObjectName("label")
		self.horizontalLayout.addWidget(self.label)
		self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
		self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
		self.horizontalSlider.setObjectName("horizontalSlider")
		self.horizontalLayout.addWidget(self.horizontalSlider)
		self.verticalLayout.addLayout(self.horizontalLayout)
		self.line = QtWidgets.QFrame(self.centralwidget)
		self.line.setFrameShape(QtWidgets.QFrame.HLine)
		self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.line.setObjectName("line")
		self.verticalLayout.addWidget(self.line)
		self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
		self.horizontalLayout_2.setObjectName("horizontalLayout_2")
		self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
		self.lineEdit.setObjectName("lineEdit")
		self.horizontalLayout_2.addWidget(self.lineEdit)
		self.search_btn = QtWidgets.QPushButton(self.centralwidget)
		self.search_btn.setText("")
		self.search_btn.setIcon(qta.icon('fa.search'))
		self.search_btn.setIconSize(QtCore.QSize(21, 21))
		self.search_btn.setObjectName("search_btn")
		self.horizontalLayout_2.addWidget(self.search_btn)
		self.verticalLayout.addLayout(self.horizontalLayout_2)
		self.verticalLayout_2 = QtWidgets.QVBoxLayout()
		self.verticalLayout_2.setContentsMargins(-1, -1, -1, 5)
		self.verticalLayout_2.setObjectName("verticalLayout_2")
		self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
		self.horizontalLayout_3.setObjectName("horizontalLayout_3")
		self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
		self.scrollArea.setWidgetResizable(True)
		self.scrollArea.setObjectName("scrollArea")
		self.scrollAreaWidgetContents = QtWidgets.QWidget()
		self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 489, 365))
		self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
		self.scrollArea.setWidget(self.scrollAreaWidgetContents)
		self.horizontalLayout_3.addWidget(self.scrollArea)
		self.gridLayout_2 = QtWidgets.QGridLayout()
		self.gridLayout_2.setObjectName("gridLayout_2")
		self.verticalLayout_5 = QtWidgets.QVBoxLayout()
		self.verticalLayout_5.setObjectName("verticalLayout_5")
		self.label_2 = QtWidgets.QLabel(self.centralwidget)
		self.label_2.setObjectName("label_2")
		self.verticalLayout_5.addWidget(self.label_2)
		self.gridLayout_2.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
		self.verticalLayout_6 = QtWidgets.QVBoxLayout()
		self.verticalLayout_6.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
		self.verticalLayout_6.setObjectName("verticalLayout_6")
		self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
		self.horizontalLayout_6.setObjectName("horizontalLayout_6")
		self.verticalSlider = QtWidgets.QSlider(self.centralwidget)
		self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
		self.verticalSlider.setObjectName("verticalSlider")
		self.verticalSlider.setMaximum(100)
		self.horizontalLayout_6.addWidget(self.verticalSlider)
		self.verticalLayout_6.addLayout(self.horizontalLayout_6)
		self.gridLayout_2.addLayout(self.verticalLayout_6, 1, 0, 1, 1)
		self.horizontalLayout_3.addLayout(self.gridLayout_2)
		self.verticalLayout_2.addLayout(self.horizontalLayout_3)
		self.verticalLayout.addLayout(self.verticalLayout_2)
		self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

		MainWindow.setCentralWidget(self.centralwidget)
		self.menubar = QtWidgets.QMenuBar(MainWindow)
		self.menubar.setGeometry(QtCore.QRect(0, 0, 568, 22))
		self.menubar.setObjectName("menubar")
		self.menuAbout = QtWidgets.QMenu(self.menubar)
		self.menuAbout.setObjectName("menuAbout")
		MainWindow.setMenuBar(self.menubar)
		self.actionsd = QtWidgets.QAction(MainWindow)
		self.actionsd.setObjectName("actionsd")
		self.menuAbout.addAction(self.actionsd)
		self.menubar.addAction(self.menuAbout.menuAction())

		self.retranslateUi(MainWindow)
		QtCore.QMetaObject.connectSlotsByName(MainWindow)

	def retranslateUi(self, MainWindow):
		_translate = QtCore.QCoreApplication.translate
		MainWindow.setWindowTitle(_translate("MainWindow", "YAudio"))
		self.label.setText(_translate("MainWindow", "00:00:00"))
		self.lineEdit.setPlaceholderText(_translate("MainWindow", "Typing search words"))
		self.label_2.setText(_translate("MainWindow", "Volume"))
		self.menuAbout.setTitle(_translate("MainWindow", "Help"))
		self.actionsd.setText(_translate("MainWindow", "About"))

